# Generated by Django 6.1.1 on 2026-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Bot MQL5, Calculadora de Aranceles', max_length=200)),
                ('descripcion', models.TextField(help_text='Explica para qué sirve o cómo usarlo.')),
                ('categoria', models.CharField(choices=[('TRADING', 'Trading e Indicadores MT5'), ('FISCAL', 'Ciencias Fiscales y Aranceles'), ('YOUTUBE', 'Recursos de YouTube / Edición')], default='TRADING', max_length=20)),
                ('archivo', models.FileField(help_text='Sube aquí el PDF, .ex5, o .zip', upload_to='archivos_descargables/')),
                ('descargas', models.IntegerField(default=0, editable=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
